recipes: Switch linting to `cros lint`
This upgrades our linting to from pylint-2.7 to pylint-2.13. It also
allows us to start linting non-python files (ex. shell, OWNER).

This CL does the following:
* Switches our linting to `cros lint`
* Puts our linting hook in PRESUBMIT.cfg
* Fixes all linting problems exposed by pylint-2.13
* Adds consider-using-f-string to our disabled checks in pylintrc,
  because there were just too many to handle

BUG=b:295339641
TEST=`cros lint {lots of directories}`
TEST=make a lint error, and try to upload
TEST=test'n'train

Change-Id: I3d3a15852e23045683c8446915e2b7f5eeaafa49
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/infra/recipes/+/4771190
Auto-Submit: Greg Edelston <gredelston@google.com>
Reviewed-by: Julio Hurtado <juahurta@google.com>
Reviewed-by: Benjamin Shai <bshai@google.com>
Commit-Queue: Greg Edelston <gredelston@google.com>

diff --git a/recipe_modules/labpack/scripts/run-build-with-current-recipes b/recipe_modules/labpack/scripts/run-build-with-current-recipes
--- a/recipe_modules/labpack/scripts/run-build-with-current-recipes
+++ b/recipe_modules/labpack/scripts/run-build-with-current-recipes
@@ -19,15 +19,16 @@ test -n "$1" || die 'must provide build'
 
 td="$(mktemp -d)" || die 'failed to make temporary directory'
 
-./get-builder "$1" | ./add-stanza "$2" > "$td"/job.json || die 'failed to create file'
-test -f "$td"/job.json || die 'file does not exist'
+./get-builder "$1" | ./add-stanza "$2" > "${td}"/job.json \
+  || die 'failed to create file'
+test -f "${td}"/job.json || die 'file does not exist'
 
 edit_file() {
-  ${VISUAL-vim} "$td"/job.json
-  if test -z "$(cat <"$td"/job.json)"; then
+  ${VISUAL-vim} "${td}"/job.json
+  if test -z "$(cat <"${td}"/job.json)"; then
     return 0
   fi
-  if python3 -m json.tool "$td"/job.json >/dev/null; then
+  if python3 -m json.tool "${td}"/job.json >/dev/null; then
     return 0
   fi
   return 1
@@ -35,9 +36,9 @@ edit_file() {
 
 edit_file || die 'failed to edit file'
 
-if test -z "$(cat <"$td"/job.json)"; then
+if test -z "$(cat <"${td}"/job.json)"; then
   1>&2 printf '%s\n' "file empty: launch aborted"
   exit 0
 fi
 
-cat "$td"/job.json | led edit-recipe-bundle | led launch
+<"${td}"/job.json led edit-recipe-bundle | led launch
